### ISSUE TITLE
Hide booking times that have already passed

### ISSUE THREAD

**Issue by andrewhilson** [CovidEngine/vaxxnz#11]
Looking for appointments renders appointments today (which is good) but shows times that have passed (eg. Pharmacy in Rosedale, Auckland showing appointments for this morning)

**Comment by andrewhilson** [comment]
![D7831BA2-FCE7-4BB9-93B1-1288A342083B](https://user-images.githubusercontent.com/4552220/132122837-0c702ee3-473d-4bbb-b6f9-63592537e060.png)

**Comment by waltzaround** [comment]
Cheers for that @andrewhilson - we're working on walk-in venues atm, and this has been queued up next

PRs are welcome if you're keen to fix 🔥
