### ISSUE TITLE
Setting location by a city doesn't retrieve the city name

### ISSUE THREAD

**Issue by tausani-ah-chong** [CovidEngine/vaxxnz#111]
**Describe the bug**
Setting location by a city doesn't retrieve the city name

**To Reproduce**
1. Go to 'vaxx.nz'
2. Click on `set your location` to any city/region e.g. Rotorua
3. placeName gets set to either lat or lng in both URL and location picker

**Screenshots**
<img width="1792" alt="Screen Shot 2021-09-10 at 10 15 05 PM" src="https://user-images.githubusercontent.com/58315812/132841774-2f83aa3a-6b51-4d21-8fe5-af4a36faa1d0.png">
<img width="1792" alt="Screen Shot 2021-09-10 at 10 15 09 PM" src="https://user-images.githubusercontent.com/58315812/132841790-ffba773b-25b3-4998-9215-a6747d9f1ba3.png">

**Device:**
 - Device: MacBook Pro
 - Browser: Firefox

**Additional context**
This is probably due to us setting placeName params by suburb.

**Comment by noway** [comment]
makes sense. i'll look into it

**Comment by gpoliko** [comment]
Seems to be the same for certain suburbs.

![image](https://user-images.githubusercontent.com/60165179/132846569-b10c330d-f1ca-45b3-a405-ca65d14f52a2.png)

![image](https://user-images.githubusercontent.com/60165179/132846654-56727530-e5ae-4771-aed0-ad3f5cd12bfe.png)

**Comment by tausani-ah-chong** [comment]
@noway Apologies if you've already started having a look into this, but I've potentially got a fix for this while having a look into #90

**Comment by noway** [comment]
Brilliant, thanks for tackling this!

**Comment by tausani-ah-chong** [comment]
> Brilliant, thanks for tackling this!

Welcome!
