### ISSUE TITLE
DX: GH action for prettier

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#117]
There's currently an outstanding PR for GH action for prettier. Tracking the progress here as well.

**Comment by rquitales** [comment]
#87 contains the GH action to ensure that all files are prettified when a PR is created against the main branch. This PR is currently being blocked as not all files within the codebase is prettified yet. This needs to happen first.

**Comment by noway** [comment]
@rquitales nice work 👍🏻  clean PR, was able to merge with no issues! I subsequently fixed the build in #161

Thanks a lot!! 💯
