### ISSUE TITLE
Add an on-brand cookie banner to the website

### ISSUE THREAD

**Issue by olafwrieden** [CovidEngine/vaxxnz#119]
**Is your feature request related to a problem? Please describe.**
It's good practice to supply a cookie notice on the website as we have implemented GA and potentially other cookies.

**Describe the solution you'd like**
1. Design an unobtrusive cookie notification that looks better and more on-brand than the default `react-cookie-consent` library banner.
2. Implement a cookie notice library that supports the design.
3. Memorise consent for 6 months (usually a built-in option with cookie consent libraries, or manually store in `localStorage`)

**Additional resources**
https://www.npmjs.com/package/react-cookie-consent

**Comment by Abhijnan-Bajpai** [comment]
Hey @olafwrieden, I would like to work on this, could I be assigned?

**Comment by olafwrieden** [comment]
For sure @Abhijnan-Bajpai - I'd like to see if we can customise the banner drastically, as the default provided by https://www.npmjs.com/package/react-cookie-consent looks terrible.

Please liaise with the `#design` channel and @waltzaround (Walt) to come up with an on-brand design. Maybe we can have it floating left or right bottom corner? Up to the design team.

I'll be in the Discord today so ping me if you need a hand getting set up technically. I saw Ilia has already shared the DEV contributor guide with you earlier.

**Comment by Abhijnan-Bajpai** [comment]
> For sure @Abhijnan-Bajpai - I'd like to see if we can customise the banner drastically, as the default provided by https://www.npmjs.com/package/react-cookie-consent looks terrible.
> 
> Please liaise with the `#design` channel and @waltzaround (Walt) to come up with an on-brand design. Maybe we can have it floating left or right bottom corner? Up to the design team.
> 
> I'll be in the Discord today so ping me if you need a hand getting set up technically.

Hey thanks for pointing me in the right direction, but I don't have the link for the discord server. Could you send it over to abhijnanbajpai@outlook.com, if it's not to be disclosed publicly.

**Comment by olafwrieden** [comment]
@Abhijnan-Bajpai the community is here: https://discord.gg/f3dDdGfk - Join, intro yourself, read contributor guide in our repo, and tag me if you need help

**Comment by oeed** [comment]
I think the sentiment from Discord is that this mightn't be necessary to show, but it's an open discussion: https://discord.com/channels/884578058911219743/884714023323586600/886006824061517855

**Comment by waltzaround** [comment]
If we do, imo only show in europe

**Comment by olafwrieden** [comment]
> If we do, imo only show in europe

I think this is a good first issue for @Abhijnan-Bajpai. Could we get a design for them to work with? Let's build the prototype, deploy it to PR and see what we collectively think. The defaults on this page are hideous https://www.npmjs.com/package/react-cookie-consent#examples

**Comment by Abhijnan-Bajpai** [comment]
@olafwrieden did we get any designs for this?

**Comment by olafwrieden** [comment]
> @olafwrieden did we get any designs for this?

Feel free to get started without one. I know there is some debate on whether this will make it into the final product as it introduces an additional step - therefore, it should be as light as possible. Please reach out to the #design or #dev chat and tag Walt (@waltzaround) for this design question.

Looking forward to what you can come up with and thank you for your contribution to vaxx.nz

**Comment by olafwrieden** [comment]
@Abhijnan-Bajpai are you still working on this? When can we expect an initial PR? If you no longer want to contribute to this, please let me know and I'll take you off the assignee list. Please also reach out as requested, in the Discord :)

**Comment by Abhijnan-Bajpai** [comment]
> @Abhijnan-Bajpai are you still working on this? When can we expect an initial PR? If you no longer want to contribute to this, please let me know and I'll take you off the assignee list. Please also reach out as requested, in the Discord :)

Yea I'm still working on a skeleton model. Will reach out to the design team once I've finished the basic model.

**Comment by olafwrieden** [comment]
Shipped in #201
