### ISSUE TITLE
Language picker should show 'English' by default

### ISSUE THREAD

**Issue by oeed** [CovidEngine/vaxxnz#123]
**Describe the bug**
Currently the language picker says 'Language' by default. For someone who doesn't know English, they mightn't know what language means and to click there to change it. I would assume though that they recognise 'English' as a place to change the language.

This stays as English once set in local storage though.

**Comment by waltzaround** [comment]
empty state also violates aria contrast accessibility

**Comment by dialectrical** [comment]
I set the placeholder of `Select` in `LanguageSelect.tsx` to English and that seems to do the trick.

(Sorry for grabbing another "good first issue"! I can leave those for others if y'all want)

**Comment by noway** [comment]
thanks to @dialectrical for tackling this!
