### ISSUE TITLE
Border width is inconsistent across the website

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#126]
**Describe the bug**
We use a variety of border widths. Looks untidy.

**To Reproduce**
1. Go to website
2. Click into a "Open today" website
3. " Walk-in vaccinations available" border is different from calendar border

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132929582-aac2e00e-e2bb-484e-a3ff-345b6d6b17e2.png)

**Additional context**
1 pixel should be good everywhere

**Comment by dialectrical** [comment]
Submitted a PR with a fix.

Since the border widths ought to be consistent, though, is there some way to centralize the modal styling so future changes don't need to go crawling through multiple files?

**Comment by noway** [comment]
Thank you!!
