### ISSUE TITLE
Use AddressFinder.nz for reverse geocoding. 

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#132]
**Is your feature request related to a problem? Please describe.**
We switched Google Autocomplete to AddressFinder.nz autocomplete, but:
We still use Google Reverse Geocoding to fetch suburb name for the "Use my current location" feature.
![image](https://user-images.githubusercontent.com/2031472/132931893-73e7a86a-f3a2-4c60-b900-3a7b1d121338.png)

**Describe the solution you'd like**
Can we use https://addressfinder.nz/api/nz/address/reverse_geocode/ to replace Google Reverse Geocoding? 

**Additional context**
The documentation says we need both API KEY and API SECRET, does it mean we have to have a backend? We want to stay 100% static to reduce number of moving parts and be web scale.
If we absolutely HAVE TO have a server, we can deploy a [Netlify Function](https://www.netlify.com/products/functions/)? I'd rather not tho

**Comment by noway** [comment]
This will allow us to drop Google Maps API JS library completely and up our Lighthouse score!!

**Comment by olafwrieden** [comment]
Just did some reading up on this, and it looks like the secret should only be supplied for server-to-server requests. It makes me think it's possible without a backend.. but would have to test this to be certain. https://addressfinder.nz/api/nz/address/reverse_geocode/

<img width="958" alt="Screen Shot 2021-09-13 at 7 12 06 PM" src="https://user-images.githubusercontent.com/42084239/133057292-ae584d7b-db6d-45ae-bfc0-07f95dd0c18d.png">

**Comment by rquitales** [comment]
Just looked into this, looks like it is possible to make a client to server request. Will create a PR for this soon.

**Comment by olafwrieden** [comment]
This was closed in #190
