### ISSUE TITLE
Scraping issues

### ISSUE THREAD

**Issue by waltzaround** [CovidEngine/vaxxnz#133]
**Describe the bug**
website displays wrong time

**To Reproduce**
1. Go to 'vaxx.nz'
2. look at some of the walk-in locations
3. compare the time

**Screenshots**

![Screen Shot 2021-09-11 at 3 13 05 PM](https://user-images.githubusercontent.com/9004833/132934451-068c3c54-d6be-425f-9af2-714774245296.png)
![Screen Shot 2021-09-11 at 3 12 22 PM](https://user-images.githubusercontent.com/9004833/132934455-a7ea9e25-7ded-4789-8a2b-5fa0bb2fa54a.png)

**Comment by noway** [comment]
i'll fix phone number as well

**Comment by noway** [comment]
I fixed that and made a new issue for telephone numbers
