### ISSUE TITLE
When closing the modal for a date, for a split second it shows an empty modal

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#145]
**Describe the bug**
When closing the modal for a date, for a split second it shows an empty modal. See screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to website
2. Click on any date
3. Click outside of modal
4. For a split second, it shows an empty modal

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132938549-5d430693-d9c7-493e-a831-6b90e545c2d4.png)

**Additional context**
Just a wrinkle, we're probably hiding content too early for one reason or another. Would be nice to fix.

**Comment by MinhPhu0304** [comment]
Fixed with PR
