### ISSUE TITLE
Create Terms and Conditions page

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#146]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a website doesn't have T's and C's. Doesn't look very credible.

**Describe the solution you'd like**
We should write a terms and conditions or ToS file! 

**Additional context**
Probably good idea to add a disclaimer there that we try our best, but we do not guarantee the correctness of data.

**Comment by rodrigohdiaz** [comment]
I'm working on this

**Comment by noway** [comment]
thanks to @rodrigohdiaz for getting this done 💯
