### ISSUE TITLE
Missing 'Address' translation

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#158]
**Describe the bug**
There is a missing 'Address' translation to be included somewhere in the code (eventhough the translation json file as 'Address' in the 'Core')

**To Reproduce**

1. Go to website
2. Click on Open-today (not crowdsourced)

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132967733-ac4e35d7-37e1-4553-a239-13f538986732.png)
![image](https://user-images.githubusercontent.com/2031472/132967735-bbb53372-8223-473f-823a-648b1ead0603.png)

**Additional context**
Probably forgot to make that string dynamic?

**Comment by geeksteph** [comment]
I'll pick this up. Pls assign this to me.

**Comment by noway** [comment]
Thanks @geeksteph :-)
