### ISSUE TITLE
Note that not all booking options are searched

### ISSUE THREAD

**Issue by orb16** [CovidEngine/vaxxnz#17]
The header on your page says "See every available vaccination booking slot near you." 

But I'm not sure it's showing the booking slots that are available that are outside the official booking system? There's quite a few at bargain chemist in CHCH https://www.bargainchemist.co.nz/pages/covid-19-vaccination as well as Unichem in CHCH https://unichemcashelpharmacy.gettimely.com/ From what I could see your system doesn't check those?

It might be worth changing the wording to note there are other options (maybe just if someone puts in a CHCH address)?

**Comment by oeed** [comment]
Thanks for alerting us! Unichem Cashel appears to not be included on the bookmyvaccine.nz website data, hence why it's not included. It seems many Unichem pharmacies don't list on the website, the ones just listing their phone number [here](https://www.unichem.co.nz/article?id=41502) seem to be missing.

We'd definitely like to add those, but at this stage we want to get the data for the majority of locations correct. It'll probably require some communication with Unichem.


Likewise with Bargain Chemist, they don't allow you to book through bookmyvaccine.nz. They have their own booking system so it'll require some time to integrate that in that can't be prioritised just yet.

**Comment by noway** [comment]
We offer crowdsourced locations now. Cheers
