### ISSUE TITLE
DX: too many files to touch to add a translation

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#174]
**Describe the bug**
to add a translation we now need to update a lot of typescript files:

 src/translations/index.ts 
 src/translations/resources.ts 
 src/utils/locale.ts 

there's probably a way to reduce number of those places

**Additional context**
We can probably generate supported locale arrays automagically based on just one array somewhere.

**Comment by olafwrieden** [comment]
Would be cool if someone can add the locale to these files programmatically when the `yarn run sync:18n` script runs.

We already have the locale code (based on translation filename) at that point, so it would just be a matter of writing it to the above-mentionedfiles.

**Comment by olafwrieden** [comment]
Nice, the `supportedLngs` in `index.ts` is optional but recommended, worst case we can strip it out and reduce from 3 to 2 files.
