### ISSUE TITLE
Format slot times according to locale

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#187]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when time slots are not in my language
![image](https://user-images.githubusercontent.com/2031472/133036360-25aaa729-48be-4343-9434-1743c3704190.png)

**Describe the solution you'd like**
I've tried using `toLocaleTimeString`, but had little luck? It seemed a bit buggy, maybe just me. Maybe there's a `date-fns` function for this?

**Additional context**
Gotta watch out for "00:00 pm" (which doesn't make any sense, should be "12:00 pm"). Last time I tried I stumbled into that.

**Comment by KevinSJ** [comment]
Hey @noway , I would like work on this. Based on code used in other components, I'm not sure what's the preferred way to implement. We could import i18next and get the language code and replace the hard coded `en-NZ` with that (similar to CalendarModalContent component), or we can wrap the parse with another format function from `data-fns`. What's the issue you were having with `toLocaleString`?

**Comment by noway** [comment]
@KevinSJ `toLocaleString` would output weird string like "00:00pm" for noon for example. In terms of organising code,  doing something like https://github.com/CovidEngine/vaxxnz/blob/f118a543a1412c4645656ceb2774f94aa91fec6b/src/utils/distance.ts#L12 would be nice
