### ISSUE TITLE
Write `<Select` component which mimics `baseui/select`

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#188]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when page loads slowly due to bundle size

**Describe the solution you'd like**
Write `<Select` component which mimics `baseui/select`, but much smaller.

**Additional context**
According to Minh's findings, `baseui/select` is the biggest package in our bundle.

**Comment by Supesu** [comment]
i'll have a go at this

**Comment by noway** [comment]
Hi @Supesu, we've recently removed `react-markdown`, so `baseui/select` is the next biggest package to remove in our bundle 🚀 
![image](https://user-images.githubusercontent.com/2031472/134768004-a23b8bc7-11b0-4b12-8bb0-c289e480d7cf.png)

Looking forward to your work!
