### ISSUE TITLE
Village Health - Christchurch missing

### ISSUE THREAD

**Issue by This-Is-Alex** [CovidEngine/vaxxnz#19]
Village Health - Christchurch on Lincoln road is missing from the site

**Comment by waltzaround** [comment]
hmm looks like it should be listed on the BookMyVaccine site, will investigate https://www.villagehealth.co.nz/covid-19-vaccine-information/

**Comment by waltzaround** [comment]
Might be something either with our location scraper or the managemyhealth site - will keep looking and get back to ya

**Comment by noway** [comment]
working on this now

**Comment by oeed** [comment]
We're not automatically adding new locations so this is now fixed!
