### ISSUE TITLE
DX: husky is broken on Windows machine

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#196]
**Describe the bug**
lint doesn't automatically get applied on commit on Windows machine

**To Reproduce**

1. Use a windows machine
1. Edit a file in a way that makes prettier complain
2. Commit it
3. Push it up
4. GH action complains about prettier

**Screenshots**
GH action complains about prettier:
![image](https://user-images.githubusercontent.com/2031472/133249332-ae900d37-9b53-4d7c-a631-bfd054f6ee7d.png)

**Additional Info:**
Found by @geeksteph . She is using Git Bash I think

**Comment by olafwrieden** [comment]
@noway can you confirm that this was closed in #198, then close the issue?

**Comment by noway** [comment]
should be good 👍🏻
