### ISSUE TITLE
A link to cancel/change my vaccination

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#206]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm booking a new vaccine, but it's hard to change my previous booking that I made before.

**Describe the solution you'd like**
Add a "Cancel/Change" button next to "Book my vaccine" button

**Additional context**
Nicola made this suggestion originally. 
Designs:
![image](https://user-images.githubusercontent.com/2031472/133404513-43b08131-cea2-4bd6-b37a-08992f421ba6.png)

**Comment by aar-ish** [comment]
Hey @noway I would like to contribute to this issue
