### ISSUE TITLE
Locations are not hidden in Date Modal if availability was updated to zero via the real-time MOH update

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#221]
**Describe the bug**
Locations are not hidden in Date Modal if availability was updated to zero via the real-time MOH update

**To Reproduce**

1. Go to website
2. Click on a very in-demand day like today
3. Real time update will kick inn
4. If the location becomes fully booked out, it is still visible.

**Screenshots**
![Screen Shot 2021-09-17 at 5 41 43 PM](https://user-images.githubusercontent.com/2031472/133731765-f494b847-9de2-4ea4-8851-469b21f1c236.png)

**Additional context**
Only happens because of real time update. We should filter out locations which have 0 slots.

**Comment by JacksonLaw** [comment]
I'll try fix this today

**Comment by JacksonLaw** [comment]
https://github.com/CovidEngine/vaxxnz/pull/225

**Comment by noway** [comment]
nicely done @JacksonLaw 💯
