### ISSUE TITLE
Link for map directions broken

### ISSUE THREAD

**Issue by william0884** [CovidEngine/vaxxnz#23]
Hello,

An example where link to map is broken: 

Epsom Vaccination Centre
382 Manukau Road Epsom, Auckland 1344. Parking at Alexandra Park, entry from 30 Campbell Crescent. (4km away)

And the link for walking direction: 
https://www.google.com/maps?t=r&daddr=382+Manukau+Road+Epsom,+Auckland+1344.+Parking+at+Alexandra+Park,+entry+from+30+Campbell+Crescent.&dirflg=w

The link shouldn't include the Parking info. Have included screenshot of maps unable to find it. 

![epson](https://user-images.githubusercontent.com/65285647/132171657-1badd57a-1d52-4f02-8289-57fd7d9100d1.PNG)

Maps would work if the link was: 
https://www.google.com/maps?t=r&daddr=382+Manukau+Road+Epsom,+Auckland+1344

Thanks,
William.

**Comment by waltzaround** [comment]
ty for this @william0884 - queued up to fix

**Comment by oeed** [comment]
This is because the address data is rather poor, we'll change to using lat long instead.

**Comment by oeed** [comment]
Fixed by #31
