### ISSUE TITLE
Scroll is a bit janky if you go into a calendar day page

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#234]
**Describe the bug**
When on mobile, going to calendar day page flickers.

**To Reproduce**

1. Open vaxx.nz on a phone
2. Scroll down a few screens
2. Click on a date
3. Observe a flicker between page changes

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/134010086-18d6714f-4450-42dd-8e5a-66fb98bae0d2.png)
![image](https://user-images.githubusercontent.com/2031472/134010109-293edfc8-68c8-424f-8f3e-4698fa65ea76.png)
![image](https://user-images.githubusercontent.com/2031472/134010118-80703fde-cf81-4232-a963-eb7a1a151e3f.png)

**Additional context**
The issue is here: https://github.com/CovidEngine/vaxxnz/blob/main/src/scroll.ts#L29 we useEffect with location.pathname dependency, but that only gets applied on the next render - thus rendering 1 frame with an old scroll position.

**Comment by JacksonLaw** [comment]
https://github.com/CovidEngine/vaxxnz/pull/252
