### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by olafwrieden** [CovidEngine/vaxxnz#253]
Need to internationalise these parts:

**1. Calendar.tsx** - @geeksteph 
<img width="1639" alt="Screen_Shot_2021-09-22_at_6 59 50_PM" src="https://user-images.githubusercontent.com/42084239/134315000-e883a51a-e13c-427b-8f8a-1b4b0c7a5c90.png">

**2. Fix this:**
<img width="1158" alt="Screen Shot 2021-09-22 at 7 06 03 PM" src="https://user-images.githubusercontent.com/42084239/134315455-11471067-f23e-427b-bb57-0051868473c7.png">

**3. Internationalise this**
<img width="930" alt="Screen Shot 2021-09-22 at 7 11 17 PM" src="https://user-images.githubusercontent.com/42084239/134316202-9c44d3ee-93c4-4591-b346-edb8636e3214.png">

**Comment by geeksteph** [comment]
@olafwrieden For #2, do you mean we want to change the "sectionHeader" to "Other Vaccination Locations Open Today" in common_en-NZ.json?

**Comment by olafwrieden** [comment]
> @olafwrieden For #2, do you mean we want to change the "sectionHeader" to "Other Vaccination Locations Open Today" in common_en-NZ.json?

No that part does not need to be changed in translations, please make this change in code:
<img width="1381" alt="Screen Shot 2021-09-22 at 7 22 07 PM" src="https://user-images.githubusercontent.com/42084239/134318495-fa03cc43-7fdf-409c-be0d-d299488084d9.png">

**Comment by geeksteph** [comment]
@olafwrieden I'm not familiar with typescript and React. For CalendarError.tsx, which of the below should I import for it to recognise the t in {t("core.mistake")} ?

- import { useTranslation } from "react-i18next";

- import i18next from "i18next";

-

**Comment by olafwrieden** [comment]
You'll need `import { useTranslation } from "react-i18next";`

`const { t } = useTranslation("common");`

Then you can do something like: `<h2>{t("walkins.sectionHeader")}</h2>` -> or whatever the translation key is

**Comment by geeksteph** [comment]
I have done the changes plus extra missing ones I found. Compile and hit error, pls advise. Refer pull request #251

**Comment by olafwrieden** [comment]
Closed in #251
