### ISSUE TITLE
DX: Switch `<Spinner` to `<StyledSpinnerNext` from baseui

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#278]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when baseui complains about deprecated Spinner
![image](https://user-images.githubusercontent.com/2031472/134629843-b13ee88b-354b-4773-a11e-4e5216897324.png)

**Describe the solution you'd like**
Switch to `StyledSpinnerNext`

**Additional context**
The spinner is this.
![image](https://user-images.githubusercontent.com/2031472/134630030-91fe5f90-cc97-4b17-af10-70b1d3a25be7.png)

**Comment by Legendarytruth** [comment]
Hey if possible I would like to take a crack at it!

**Comment by noway** [comment]
@Legendarytruth sweet! assigned you

**Comment by noway** [comment]
Thanks for solving this!
