### ISSUE TITLE
Minor - Link to 'bookmyvaccine.nz' broken in README

### ISSUE THREAD

**Issue by tausani-ah-chong** [CovidEngine/vaxxnz#29]
Hey team!

Loving the work so far! This is inspiring to me as a junior dev. Would love to help out where I can :)

----------------------

Just a minor fix to link in the first paragraph of the `README`

The link currently takes you to here: 

<img width="450" alt="Screen Shot 2021-09-07 at 6 40 38 AM" src="https://user-images.githubusercontent.com/58315812/132253648-d352474e-bca8-467d-a777-cf4b14a5242c.png">

<img width="1039" alt="Screen Shot 2021-09-07 at 6 40 25 AM" src="https://user-images.githubusercontent.com/58315812/132253634-21422457-a670-4c46-a757-d49241792a6b.png">

**Comment by noway** [comment]
thanks for the fix!
