### ISSUE TITLE
Replace `react-responsive` with proper media queries

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#303]
**Is your feature request related to a problem? Please describe.**
Our bundle size continuous to be a big priority for us in order to reduce Core Web Vitals.
`react-responsive` takes up 45KB of our bundle.

**Describe the solution you'd like**
Replace `react-responsive` with proper media queries. 

**Additional context**
This would require changing some components from using inline styles to using either .css styles or `styled-components`-like css (our preferred CSS-in-JS library is `styletron-react`)

**Comment by Supesu** [comment]
Yeah i'll be down to take this on
