### ISSUE TITLE
Show number of vaccination sites on calendar container

### ISSUE THREAD

**Issue by rquitales** [CovidEngine/vaxxnz#37]
When using the app, I was excited to see days that had a lot of available time slots, only to be disappointed when drilling down onto that day and discovering that the slots are only for 1 vaccination centre that is in an inconvenient location.

I propose adding another line of text under each calendar entry that indicates how many locations there are as well.

**Comment by waltzaround** [comment]
Thoughts on trying out distance from centre instead?

**Comment by rquitales** [comment]
Closing this out. Will maintain own fork.
