### ISSUE TITLE
Going back after setting the location does not revert to the default location

### ISSUE THREAD

**Issue by oeed** [CovidEngine/vaxxnz#39]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://vaxx.nz/'
2. Pick a location, i.e. 'Epsom'
3. Press the back button, it'll leave Epsom showing in the location picker.

**Comment by Francismb** [comment]
https://github.com/CovidEngine/vaxxnz/pull/63

**Comment by oeed** [comment]
Fixed by #63
