### ISSUE TITLE
Create a submission form for vaccine sites that aren't listed on BookMyVaccine

### ISSUE THREAD

**Issue by waltzaround** [CovidEngine/vaxxnz#41]
As a covid vaccine site operator who isnt listed on BookMyvaccine
I want to submit details about my vaccine site in a form
So the Vaxx team can receive my site information for review so they can put it on the website

Create a submission form for vaccine sites that aren't listed on BookMyVaccine

**Comment by oeed** [comment]
@waltzaround can you clarify what a one off site is?

**Comment by waltzaround** [comment]
editing now

**Comment by noway** [comment]
We need a design for this.

**Comment by olafwrieden** [comment]
How can we move this issue forward @waltzaround and @noway?
My idea: Similar to Contact Us, let's simply create an Airtable form.

I've looked into sending a React form as an issue or PR straight to GitHub, but it will require way too much complexity and potentially a backend to do the auth. If you agree, let's just ship this as an Airtable form instead.

Here are the fields we currently store for crowdsourced locations:

```javascript
{
  isCrowdSourced: true,
  name: "The Palms Medical Centre",
  address: "445 Ferguson Street, Palmerston North 4410",
  lat: -40.3565159,
  lng: 175.6194385,
  instructions: [Instruction.allowsBookings],
  website: "https://palmsmedical.co.nz/",
  telephone: "06 354 7737",
  additionalInformation:
    "We are currently by appointment only from the hours of 9am-4pm Tuesday to Friday. We presently have quite a bit of availability. Anyone wanting to book can call the medical centre on 06 354 7737.",
  openingHours: [
    { day: 1, isOpen: false },
    { day: 2, isOpen: true, hours: "9:00 AM – 4:00 PM" },
    { day: 3, isOpen: true, hours: "9:00 AM – 4:00 PM" },
    { day: 4, isOpen: true, hours: "9:00 AM – 4:00 PM" },
    { day: 5, isOpen: true, hours: "9:00 AM – 4:00 PM" },
    { day: 6, isOpen: false },
    { day: 0, isOpen: false },
  ]
}
```

**Comment by noway** [comment]
We should redirect them to healthpoint instead. An FAQ entry which lists Healthpoint contact?

**Comment by wseagar** [comment]
Closing this as we're not doing it. Contact form works good enough and we don't want to maintain a database of locations. Should redirect people to healthpoint.
