### ISSUE TITLE
Page stuck in infinite loading state when no location is set

### ISSUE THREAD

**Issue by waltzaround** [CovidEngine/vaxxnz#47]
Page wont load if no location is set 

**To Reproduce**
1. Go to 'vaxx.nz
2. dont set a location
3. wait for listings to load

**Comment by Francismb** [comment]
I was not able to reproduce this, I believe the location defaults to Auckland and you cannot clear the selection?

**Comment by oeed** [comment]
Appears to have been internet issues by the reported error.
