### ISSUE TITLE
`Warning: validateDOMNesting(...): <h3> cannot appear as a descendant of <p>.`

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#61]
**Describe the bug**
`Warning: validateDOMNesting(...): <h3> cannot appear as a descendant of <p>.` when openning a day

**To Reproduce**
1. run on local
2. open day
3. see it in console in devtools

**Additional context**
it's just a react warning, needs fixing pretty annoying

**Comment by BenRauzi** [comment]
Can be closed

**Comment by noway** [comment]
True, thank you guys!
