### ISSUE TITLE
Language select label doesn't change when selecting another language

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#64]
**Describe the bug**
Language select label doesn't change when selecting another language

**To Reproduce**
1. Go to vaxx.nz
2. Click on English
3. Select some other language
4. The language label doesn't change

**Additional context**
Something is up with the way we're using Select component from base web

**Comment by Francismb** [comment]
Ill take a look at this one 👍

**Comment by Francismb** [comment]
https://github.com/CovidEngine/vaxxnz/pull/72

**Comment by noway** [comment]
thank you!
