### ISSUE TITLE
Loading state layout is not properly aligned

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#74]
**Describe the bug**
Loading state layout is not properly aligned

**To Reproduce**
1. Switch between radius
2. observe loading state
3. styling is not right

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132622255-59350fbd-4eb4-4ad0-a68d-cd416120cae4.png)

**Comment by Abhijnan-Bajpai** [comment]
Hey @noway , I would like to work on this. Could I be assigned this issue?

**Comment by noway** [comment]
@Abhijnan-Bajpai sorry for late replay, yeah go ahead

**Comment by noway** [comment]
this has been done
