### ISSUE TITLE
Prettier pre-commit hook

### ISSUE THREAD

**Issue by oeed** [CovidEngine/vaxxnz#77]

**Comment by Francismb** [comment]
Will have a look into this using Github actions. I presume it is to ensure consistent styles?

**Comment by Francismb** [comment]
Solving this with husky + pretty-quick npm packages.

**Comment by noway** [comment]
We shipped pre-commit hook (props to all the great PRs above, nice work!), GH action for it is still outstanding, but that's outside of scope of this particular issue.
