### ISSUE TITLE
Move 'other location' data in to a separate fetched file

### ISSUE THREAD

**Issue by oeed** [CovidEngine/vaxxnz#85]
Currently the data for other locations is baked in to the JS, it'd be better to fetch it separately like we do with other data.

**Comment by noway** [comment]
Let's create another repo just for crowdsourced locations. And fetch it via githubusercontent just like we do for vaxxnzlocations. Feel free to come up with a cool new name for it.

**Comment by noway** [comment]
Honestly it works perfectly fine as it is, I think it's mint.
