### ISSUE TITLE
Use URL search params as lat/lng/placeName 'state'

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#90]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it's confusing and error prone to deal with lat/lng/placeName in our code. Initial implementation was shipped on a tight timeline, it was improved a bit now, but we can make it even better.

**Describe the solution you'd like**
Only have lat/lng/placeName state in URL. If you want to change those parameters, you HAVE to push to History API.

**Additional context**
Shareable URL links is a crucial feature for us, we've seen a lot of growth through clever use of suburb links in subreddit communities. Making this feature robust is important to set up our platform for growth.

**Comment by tausani-ah-chong** [comment]
@noway I'll have a go at tackling this one!

**Comment by olafwrieden** [comment]
I believe `Use URL search params as lat/lng/placeName 'state'` has been implemented. If not, please reopen. From my understanding of the task, I can see `?placeName=` in the URL and believe state is populated accordingly.
