### ISSUE TITLE
Implement a nicer-looking error state

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#91]
**Is your feature request related to a problem? Please describe.**
The error message is a bit cluttered among other content. It needs room to breath. Maybe add an icon or an SVG image too to make it fun too?

**Describe the solution you'd like**
Design a better error state which looks better than what we have now.

**Additional context**
![image](https://user-images.githubusercontent.com/2031472/132771319-7d2c01ff-a340-4b8e-abcf-e6422b0ccba8.png)

**Comment by waltzaround** [comment]
i would suggest a min-height css container as well on the empty state to reduce the amount of CLS

https://web.dev/cls/ for reference

**Comment by waltzaround** [comment]
We have some design being worked on atm - all contributions welcome

**Comment by noway** [comment]
![image](https://user-images.githubusercontent.com/2031472/132938630-c370a7ec-3ba7-4105-9a50-2bcd5f50a4af.png)
https://www.figma.com/file/4oWThzqdwnGO0ibpbWR3zd/Vaxxtastic?node-id=213%3A641
we got a design for this! who wants to take on this issue?

**Comment by Supesu** [comment]
Hey! I'd be willing to have a go at tackling this problem

**Comment by Supesu** [comment]
Hey! I'm willing to have a go at tackling this

**Comment by olafwrieden** [comment]
@Supesu I know you are actively working on this but do give us a progress update during the day tomorrow and liaise with the team here if you have design / responsiveness questions. Beyond this, would you be keen to give #233 a shot?

**Comment by Supesu** [comment]
@olafwrieden Hey! sorry about the time it's taking although its lockdown I've still got to deal with highschool (zzz) and a couple of commissions. had a chat to Walt and Ilia earlier and i'll make sure to relay to you guys if I come across any problems / queries. I'm currently working on making it overlay the two buttons (make a booking & walk in / drive through) although after that's complete it's pretty much done. 
current estimation for completion: sometime ish tomorrow?
 ---
 I'll have to look further into #233 but i'm more then willing to give it a shot

**Comment by olafwrieden** [comment]
Merged in #249
